# Generated by Django 3.1.6 on 2021-04-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleQuestion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
                ('DifficultyLevel', models.IntegerField()),
                ('QuestionInfoId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInfo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=100)),
                ('Answered', models.BooleanField()),
            ],
        ),
    ]
