# Generated by Django 3.1.6 on 2021-04-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninfo',
            name='Answered',
            field=models.BooleanField(default=False),
        ),
    ]
