# Generated by Django 3.1.6 on 2021-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaApp', '0002_auto_20210404_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblequestion',
            name='Category',
            field=models.IntegerField(),
        ),
    ]
