# Generated by Django 3.1.6 on 2021-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaApp', '0005_remove_biblequestion_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblequestion',
            name='Answered',
            field=models.BooleanField(default=False),
        ),
    ]
